//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PngifyMe.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PngifyMe.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar.
        /// </summary>
        public static string Avatar {
            get {
                return ResourceManager.GetString("Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        public static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human Mode.
        /// </summary>
        public static string HumanMode {
            get {
                return ResourceManager.GetString("HumanMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input:.
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LayerSetup.
        /// </summary>
        public static string LayerSetup {
            get {
                return ResourceManager.GetString("LayerSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LayoutMenu.
        /// </summary>
        public static string LayoutMenu {
            get {
                return ResourceManager.GetString("LayoutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microphone.
        /// </summary>
        public static string Microphone {
            get {
                return ResourceManager.GetString("Microphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microphone Setup.
        /// </summary>
        public static string MicSetup {
            get {
                return ResourceManager.GetString("MicSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode Select:.
        /// </summary>
        public static string ModeSelect {
            get {
                return ResourceManager.GetString("ModeSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected.
        /// </summary>
        public static string NotConnected {
            get {
                return ResourceManager.GetString("NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output:.
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        public static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoothing.
        /// </summary>
        public static string Smoothing {
            get {
                return ResourceManager.GetString("Smoothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throwing.
        /// </summary>
        public static string Throwing {
            get {
                return ResourceManager.GetString("Throwing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close settings.
        /// </summary>
        public static string ToolTipCloseSettings {
            get {
                return ResourceManager.GetString("ToolTipCloseSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current speaking volume.
        /// </summary>
        public static string ToolTipCurrent {
            get {
                return ResourceManager.GetString("ToolTipCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to human activated mode.
        /// </summary>
        public static string ToolTipHuman {
            get {
                return ResourceManager.GetString("ToolTipHuman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only save, doesnt apply.
        /// </summary>
        public static string ToolTipSaveChanges {
            get {
                return ResourceManager.GetString("ToolTipSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How quickly current volume gains/loses.
        /// </summary>
        public static string ToolTipSmoothing {
            get {
                return ResourceManager.GetString("ToolTipSmoothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshhold to switch to speaking image.
        /// </summary>
        public static string ToolTipThreshhold {
            get {
                return ResourceManager.GetString("ToolTipThreshhold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to TTS pet mode with ai integration.
        /// </summary>
        public static string ToolTipTTS {
            get {
                return ResourceManager.GetString("ToolTipTTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head to general settings to authenticate with twitch.
        /// </summary>
        public static string ToolTipTwitchStatus {
            get {
                return ResourceManager.GetString("ToolTipTwitchStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treshhold.
        /// </summary>
        public static string Treshhold {
            get {
                return ResourceManager.GetString("Treshhold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTSPet.
        /// </summary>
        public static string TTSPet {
            get {
                return ResourceManager.GetString("TTSPet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTS Pet Mode.
        /// </summary>
        public static string TTSPetMode {
            get {
                return ResourceManager.GetString("TTSPetMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitch:.
        /// </summary>
        public static string Twitch {
            get {
                return ResourceManager.GetString("Twitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitch Status:.
        /// </summary>
        public static string TwitchStatus {
            get {
                return ResourceManager.GetString("TwitchStatus", resourceCulture);
            }
        }
    }
}
