//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PngifyMe.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PngifyMe.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated.
        /// </summary>
        public static string Activated {
            get {
                return ResourceManager.GetString("Activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate this state.
        /// </summary>
        public static string ActivateStateToolTip {
            get {
                return ResourceManager.GetString("ActivateStateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddLayer.
        /// </summary>
        public static string AddLayer {
            get {
                return ResourceManager.GetString("AddLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Profile.
        /// </summary>
        public static string AddNewProfile {
            get {
                return ResourceManager.GetString("AddNewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Selected Layer.
        /// </summary>
        public static string AddSelectLayerToolTip {
            get {
                return ResourceManager.GetString("AddSelectLayerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Profiles:.
        /// </summary>
        public static string AllProfiles {
            get {
                return ResourceManager.GetString("AllProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Triggers:.
        /// </summary>
        public static string AllTriggers {
            get {
                return ResourceManager.GetString("AllTriggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply and Reload.
        /// </summary>
        public static string ApplyAndReload {
            get {
                return ResourceManager.GetString("ApplyAndReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply and Save.
        /// </summary>
        public static string ApplyAndSave {
            get {
                return ResourceManager.GetString("ApplyAndSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply all changed settings and save them.
        /// </summary>
        public static string ApplyAndSaveToolTip {
            get {
                return ResourceManager.GetString("ApplyAndSaveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art.
        /// </summary>
        public static string Art {
            get {
                return ResourceManager.GetString("Art", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar.
        /// </summary>
        public static string Avatar {
            get {
                return ResourceManager.GetString("Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar Mode:.
        /// </summary>
        public static string AvatarMode {
            get {
                return ResourceManager.GetString("AvatarMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Setup.
        /// </summary>
        public static string BackGroundSetup {
            get {
                return ResourceManager.GetString("BackGroundSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Avatar State Setup.
        /// </summary>
        public static string BasicAvatarSetup {
            get {
                return ResourceManager.GetString("BasicAvatarSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blend Time.
        /// </summary>
        public static string BlendTime {
            get {
                return ResourceManager.GetString("BlendTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blending of last image, set to 0 to disable all blending.
        /// </summary>
        public static string BlendTimeToolTip {
            get {
                return ResourceManager.GetString("BlendTimeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blink.
        /// </summary>
        public static string Blink {
            get {
                return ResourceManager.GetString("Blink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blink Interval.
        /// </summary>
        public static string BlinkInterval {
            get {
                return ResourceManager.GetString("BlinkInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time between blinks.
        /// </summary>
        public static string BlinkIntervalToolTip {
            get {
                return ResourceManager.GetString("BlinkIntervalToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blink Time.
        /// </summary>
        public static string BlinkTime {
            get {
                return ResourceManager.GetString("BlinkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long character blinks.
        /// </summary>
        public static string BlinkTimeToolTip {
            get {
                return ResourceManager.GetString("BlinkTimeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChangeSound.
        /// </summary>
        public static string ChangeSound {
            get {
                return ResourceManager.GetString("ChangeSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Trigger:.
        /// </summary>
        public static string ChatTrigger {
            get {
                return ResourceManager.GetString("ChatTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTSPet will respond to any chat message starting with this, leave empty to disable.
        /// </summary>
        public static string ChatTriggerToolTip {
            get {
                return ResourceManager.GetString("ChatTriggerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your TTS Provider.
        /// </summary>
        public static string ChooseTTSProvider {
            get {
                return ResourceManager.GetString("ChooseTTSProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Selected.
        /// </summary>
        public static string ClearSelected {
            get {
                return ResourceManager.GetString("ClearSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed Mouth.
        /// </summary>
        public static string ClosedMouth {
            get {
                return ResourceManager.GetString("ClosedMouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collission speed drop:.
        /// </summary>
        public static string CollissionSpeedDrop {
            get {
                return ResourceManager.GetString("CollissionSpeedDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by:.
        /// </summary>
        public static string Createdby {
            get {
                return ResourceManager.GetString("Createdby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Profile:.
        /// </summary>
        public static string CurrentProfile {
            get {
                return ResourceManager.GetString("CurrentProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Domain:.
        /// </summary>
        public static string CustomDomain {
            get {
                return ResourceManager.GetString("CustomDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for non OpenAI Models.
        /// </summary>
        public static string CustomDomainToolTip {
            get {
                return ResourceManager.GetString("CustomDomainToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Character by:.
        /// </summary>
        public static string DefaultCharacter {
            get {
                return ResourceManager.GetString("DefaultCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Sound.
        /// </summary>
        public static string DefaultSound {
            get {
                return ResourceManager.GetString("DefaultSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to revert to default sound.
        /// </summary>
        public static string DefaultSoundToolTip {
            get {
                return ResourceManager.GetString("DefaultSoundToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Spout2.
        /// </summary>
        public static string EnableSpout2 {
            get {
                return ResourceManager.GetString("EnableSpout2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint:.
        /// </summary>
        public static string EndPoint {
            get {
                return ResourceManager.GetString("EndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Time:.
        /// </summary>
        public static string EntryTime {
            get {
                return ResourceManager.GetString("EntryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Time:.
        /// </summary>
        public static string ExitTime {
            get {
                return ResourceManager.GetString("ExitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered Words (separated with &quot;;&quot;):.
        /// </summary>
        public static string FilteredWords {
            get {
                return ResourceManager.GetString("FilteredWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter all filtered words you want to add.
        /// </summary>
        public static string FilteredWordsToolTip {
            get {
                return ResourceManager.GetString("FilteredWordsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        public static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Offset X.
        /// </summary>
        public static string GlobalOffsetX {
            get {
                return ResourceManager.GetString("GlobalOffsetX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Offset Y.
        /// </summary>
        public static string GlobalOffsetY {
            get {
                return ResourceManager.GetString("GlobalOffsetY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Settings.
        /// </summary>
        public static string GlobalSettings {
            get {
                return ResourceManager.GetString("GlobalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Zoom.
        /// </summary>
        public static string GlobalZoom {
            get {
                return ResourceManager.GetString("GlobalZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravity.
        /// </summary>
        public static string Gravity {
            get {
                return ResourceManager.GetString("Gravity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History and Test.
        /// </summary>
        public static string HistoryAndTest {
            get {
                return ResourceManager.GetString("HistoryAndTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey.
        /// </summary>
        public static string Hotkey {
            get {
                return ResourceManager.GetString("Hotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkeybox.
        /// </summary>
        public static string Hotkeybox {
            get {
                return ResourceManager.GetString("Hotkeybox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human Mode.
        /// </summary>
        public static string HumanMode {
            get {
                return ResourceManager.GetString("HumanMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import PNGs.
        /// </summary>
        public static string ImportPNGs {
            get {
                return ResourceManager.GetString("ImportPNGs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from PngTuber Plus.
        /// </summary>
        public static string ImportPngTuberPlus {
            get {
                return ResourceManager.GetString("ImportPngTuberPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Profile.
        /// </summary>
        public static string ImportProfile {
            get {
                return ResourceManager.GetString("ImportProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Text:.
        /// </summary>
        public static string InputText {
            get {
                return ResourceManager.GetString("InputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install in OBS.
        /// </summary>
        public static string InstallInOBS {
            get {
                return ResourceManager.GetString("InstallInOBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just Read, no LLM.
        /// </summary>
        public static string JustReadNoLLM {
            get {
                return ResourceManager.GetString("JustReadNoLLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if checked: will just read all messages and not respond using the llm.
        /// </summary>
        public static string JustReadNoLLMToolTip {
            get {
                return ResourceManager.GetString("JustReadNoLLMToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LayerList:.
        /// </summary>
        public static string LayerList {
            get {
                return ResourceManager.GetString("LayerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer Menu.
        /// </summary>
        public static string LayerMenu {
            get {
                return ResourceManager.GetString("LayerMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layers.
        /// </summary>
        public static string Layers {
            get {
                return ResourceManager.GetString("Layers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LayerSetup.
        /// </summary>
        public static string LayerSetup {
            get {
                return ResourceManager.GetString("LayerSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LayoutMenu.
        /// </summary>
        public static string LayoutMenu {
            get {
                return ResourceManager.GetString("LayoutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LLM.
        /// </summary>
        public static string LLM {
            get {
                return ResourceManager.GetString("LLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo by:.
        /// </summary>
        public static string LogoBy {
            get {
                return ResourceManager.GetString("LogoBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Context:.
        /// </summary>
        public static string MaxContext {
            get {
                return ResourceManager.GetString("MaxContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many messages should be kept in memory.
        /// </summary>
        public static string MaxContextToolTip {
            get {
                return ResourceManager.GetString("MaxContextToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        public static string Maximum {
            get {
                return ResourceManager.GetString("Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Bits:.
        /// </summary>
        public static string MaximumBits {
            get {
                return ResourceManager.GetString("MaximumBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Object Speed:.
        /// </summary>
        public static string MaximumObjectSpeed {
            get {
                return ResourceManager.GetString("MaximumObjectSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Tokens:.
        /// </summary>
        public static string MaxTokens {
            get {
                return ResourceManager.GetString("MaxTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many tokens the model should be allowed to respond with (1 token is roughly 1 word).
        /// </summary>
        public static string MaxTokensToolTip {
            get {
                return ResourceManager.GetString("MaxTokensToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microphone.
        /// </summary>
        public static string Microphone {
            get {
                return ResourceManager.GetString("Microphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microphone Setup.
        /// </summary>
        public static string MicSetup {
            get {
                return ResourceManager.GetString("MicSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        public static string Minimum {
            get {
                return ResourceManager.GetString("Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Bits:.
        /// </summary>
        public static string MinimumBits {
            get {
                return ResourceManager.GetString("MinimumBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum bits threshhold to react.
        /// </summary>
        public static string MinimumBitsToolTip {
            get {
                return ResourceManager.GetString("MinimumBitsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Object Speed:.
        /// </summary>
        public static string MinimumObjectSpeed {
            get {
                return ResourceManager.GetString("MinimumObjectSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model:.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input your api model name.
        /// </summary>
        public static string ModelToolTip {
            get {
                return ResourceManager.GetString("ModelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode Select:.
        /// </summary>
        public static string ModeSelect {
            get {
                return ResourceManager.GetString("ModeSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Profile Name.
        /// </summary>
        public static string NewProfileName {
            get {
                return ResourceManager.GetString("NewProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds a new trigger group.
        /// </summary>
        public static string NewTriggerToolTip {
            get {
                return ResourceManager.GetString("NewTriggerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Authenticated.
        /// </summary>
        public static string NotAuthenticated {
            get {
                return ResourceManager.GetString("NotAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected.
        /// </summary>
        public static string NotConnected {
            get {
                return ResourceManager.GetString("NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing selected.
        /// </summary>
        public static string NothingSelected {
            get {
                return ResourceManager.GetString("NothingSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenAI API Key:.
        /// </summary>
        public static string OpenAIKey {
            get {
                return ResourceManager.GetString("OpenAIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert your openai key or other provider.
        /// </summary>
        public static string OpenAIKeyToolTip {
            get {
                return ResourceManager.GetString("OpenAIKeyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Mouth.
        /// </summary>
        public static string OpenMouth {
            get {
                return ResourceManager.GetString("OpenMouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (optional).
        /// </summary>
        public static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Software/Games.
        /// </summary>
        public static string OtherSoftware {
            get {
                return ResourceManager.GetString("OtherSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance:.
        /// </summary>
        public static string Performance {
            get {
                return ResourceManager.GetString("Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Background Colour.
        /// </summary>
        public static string PickBackgroundColour {
            get {
                return ResourceManager.GetString("PickBackgroundColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick File.
        /// </summary>
        public static string PickFile {
            get {
                return ResourceManager.GetString("PickFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Folder.
        /// </summary>
        public static string PickFolder {
            get {
                return ResourceManager.GetString("PickFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        public static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to React to followers.
        /// </summary>
        public static string ReactFollowers {
            get {
                return ResourceManager.GetString("ReactFollowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will read new followers if enabled.
        /// </summary>
        public static string ReactFollowersToolTip {
            get {
                return ResourceManager.GetString("ReactFollowersToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to React to all chat messages.
        /// </summary>
        public static string ReactToAllMessages {
            get {
                return ResourceManager.GetString("ReactToAllMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to will react to any chat message.
        /// </summary>
        public static string ReactToAllMessagesToolTip {
            get {
                return ResourceManager.GetString("ReactToAllMessagesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        public static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this to read the input text (usefull to test tts voices).
        /// </summary>
        public static string ReadToolTip {
            get {
                return ResourceManager.GetString("ReadToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeem:.
        /// </summary>
        public static string Redeem {
            get {
                return ResourceManager.GetString("Redeem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement:.
        /// </summary>
        public static string Replacement {
            get {
                return ResourceManager.GetString("Replacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This phrase will replace all filtered words found in the text the ttspet is about to speak.
        /// </summary>
        public static string ReplacementToolTip {
            get {
                return ResourceManager.GetString("ReplacementToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respond.
        /// </summary>
        public static string Respond {
            get {
                return ResourceManager.GetString("Respond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this to respond to the input text.
        /// </summary>
        public static string RespondToolTip {
            get {
                return ResourceManager.GetString("RespondToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry Twitch Connection.
        /// </summary>
        public static string RetryTwitchConnection {
            get {
                return ResourceManager.GetString("RetryTwitchConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this to start twitch after enabling it, or restarting it after going offline.
        /// </summary>
        public static string RetryTwitchConnectionToolTip {
            get {
                return ResourceManager.GetString("RetryTwitchConnectionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Specs.
        /// </summary>
        public static string RunSpecs {
            get {
                return ResourceManager.GetString("RunSpecs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires save and restart to apply.
        /// </summary>
        public static string RunSpecsNote {
            get {
                return ResourceManager.GetString("RunSpecsNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, how are you?.
        /// </summary>
        public static string SampleText {
            get {
                return ResourceManager.GetString("SampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Settings.
        /// </summary>
        public static string SelectedSettings {
            get {
                return ResourceManager.GetString("SelectedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Trigger Settings:.
        /// </summary>
        public static string SelectedTriggerSetting {
            get {
                return ResourceManager.GetString("SelectedTriggerSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected layer, then click AddLayer to add it.
        /// </summary>
        public static string SelectLayerToolTip {
            get {
                return ResourceManager.GetString("SelectLayerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select me :).
        /// </summary>
        public static string SelectMeToolTip {
            get {
                return ResourceManager.GetString("SelectMeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a new layer.
        /// </summary>
        public static string SelectNewLayer {
            get {
                return ResourceManager.GetString("SelectNewLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select trigger type.
        /// </summary>
        public static string SelectTriggerType {
            get {
                return ResourceManager.GetString("SelectTriggerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup transitions.
        /// </summary>
        public static string SetupTransitions {
            get {
                return ResourceManager.GetString("SetupTransitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show FPS Counter.
        /// </summary>
        public static string ShowFPSCounter {
            get {
                return ResourceManager.GetString("ShowFPSCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Hitboxes.
        /// </summary>
        public static string ShowHitbox {
            get {
                return ResourceManager.GetString("ShowHitbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoothing.
        /// </summary>
        public static string Smoothing {
            get {
                return ResourceManager.GetString("Smoothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Enabled.
        /// </summary>
        public static string SoundEnabled {
            get {
                return ResourceManager.GetString("SoundEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low is 1280x720 60fps.
        /// </summary>
        public static string SpecLow {
            get {
                return ResourceManager.GetString("SpecLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal is 1920x1080 60fps.
        /// </summary>
        public static string SpecNormal {
            get {
                return ResourceManager.GetString("SpecNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultra is 3840x2160 60fps.
        /// </summary>
        public static string SpecUltra {
            get {
                return ResourceManager.GetString("SpecUltra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Low is 960x540 60fps.
        /// </summary>
        public static string SpecVeryLow {
            get {
                return ResourceManager.GetString("SpecVeryLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprite Avatar State Setup.
        /// </summary>
        public static string SpriteAvatarSetup {
            get {
                return ResourceManager.GetString("SpriteAvatarSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support us:.
        /// </summary>
        public static string SupportUs {
            get {
                return ResourceManager.GetString("SupportUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Message (Base instructions):.
        /// </summary>
        public static string SystemMessage {
            get {
                return ResourceManager.GetString("SystemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Rain.
        /// </summary>
        public static string TestRain {
            get {
                return ResourceManager.GetString("TestRain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Throw.
        /// </summary>
        public static string TestThrow {
            get {
                return ResourceManager.GetString("TestThrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test the throwing system.
        /// </summary>
        public static string TestThrowToolTip {
            get {
                return ResourceManager.GetString("TestThrowToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test your setup.
        /// </summary>
        public static string TestYourSetup {
            get {
                return ResourceManager.GetString("TestYourSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throwing.
        /// </summary>
        public static string Throwing {
            get {
                return ResourceManager.GetString("Throwing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeStamp.
        /// </summary>
        public static string TimeStamp {
            get {
                return ResourceManager.GetString("TimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitch Integrated Throwing System (TITS) allows you to throw items at your PngTuber..
        /// </summary>
        public static string TITSExplanation {
            get {
                return ResourceManager.GetString("TITSExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TITS Setup.
        /// </summary>
        public static string TITSSetup {
            get {
                return ResourceManager.GetString("TITSSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggleable.
        /// </summary>
        public static string Toggleable {
            get {
                return ResourceManager.GetString("Toggleable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makes it so trigger removes layers if already added.
        /// </summary>
        public static string ToggleableToolTip {
            get {
                return ResourceManager.GetString("ToggleableToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will revert to default if already active..
        /// </summary>
        public static string ToggleAvatarToolTip {
            get {
                return ResourceManager.GetString("ToggleAvatarToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close settings.
        /// </summary>
        public static string ToolTipCloseSettings {
            get {
                return ResourceManager.GetString("ToolTipCloseSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current speaking volume.
        /// </summary>
        public static string ToolTipCurrent {
            get {
                return ResourceManager.GetString("ToolTipCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this to test the hit box of your character.
        /// </summary>
        public static string ToolTipHitbox {
            get {
                return ResourceManager.GetString("ToolTipHitbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to human activated mode.
        /// </summary>
        public static string ToolTipHuman {
            get {
                return ResourceManager.GetString("ToolTipHuman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only save, doesnt apply.
        /// </summary>
        public static string ToolTipSaveChanges {
            get {
                return ResourceManager.GetString("ToolTipSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How quickly current volume gains/loses.
        /// </summary>
        public static string ToolTipSmoothing {
            get {
                return ResourceManager.GetString("ToolTipSmoothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshhold to switch to speaking image.
        /// </summary>
        public static string ToolTipThreshhold {
            get {
                return ResourceManager.GetString("ToolTipThreshhold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to TTS pet mode with ai integration.
        /// </summary>
        public static string ToolTipTTS {
            get {
                return ResourceManager.GetString("ToolTipTTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head to general settings to authenticate with twitch.
        /// </summary>
        public static string ToolTipTwitchStatus {
            get {
                return ResourceManager.GetString("ToolTipTwitchStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transitions.
        /// </summary>
        public static string Transitions {
            get {
                return ResourceManager.GetString("Transitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparent.
        /// </summary>
        public static string Transparent {
            get {
                return ResourceManager.GetString("Transparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the background to transparent to capture it easier in obs.
        /// </summary>
        public static string TransparentToolTip {
            get {
                return ResourceManager.GetString("TransparentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treshhold.
        /// </summary>
        public static string Treshhold {
            get {
                return ResourceManager.GetString("Treshhold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger:.
        /// </summary>
        public static string Trigger {
            get {
                return ResourceManager.GetString("Trigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger and Effect setup.
        /// </summary>
        public static string TriggerAndEffectSetup {
            get {
                return ResourceManager.GetString("TriggerAndEffectSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger Conditions.
        /// </summary>
        public static string TriggerConditions {
            get {
                return ResourceManager.GetString("TriggerConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger Setup.
        /// </summary>
        public static string TriggerSetup {
            get {
                return ResourceManager.GetString("TriggerSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTS.
        /// </summary>
        public static string TTS {
            get {
                return ResourceManager.GetString("TTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTS Model:.
        /// </summary>
        public static string TTSModel {
            get {
                return ResourceManager.GetString("TTSModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTSPet.
        /// </summary>
        public static string TTSPet {
            get {
                return ResourceManager.GetString("TTSPet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTS Pet Mode.
        /// </summary>
        public static string TTSPetMode {
            get {
                return ResourceManager.GetString("TTSPetMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTS Pet Setup.
        /// </summary>
        public static string TTSPetSetup {
            get {
                return ResourceManager.GetString("TTSPetSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTS Provider:.
        /// </summary>
        public static string TTSProvider {
            get {
                return ResourceManager.GetString("TTSProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick your TTS provider.
        /// </summary>
        public static string TTSProviderToolTip {
            get {
                return ResourceManager.GetString("TTSProviderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTS Voice:.
        /// </summary>
        public static string TTSVoice {
            get {
                return ResourceManager.GetString("TTSVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitch:.
        /// </summary>
        public static string Twitch {
            get {
                return ResourceManager.GetString("Twitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use your channels twitch emotes, need to connect twitch to enable this.
        /// </summary>
        public static string TwitchEmotesToolTip {
            get {
                return ResourceManager.GetString("TwitchEmotesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitch Enabled.
        /// </summary>
        public static string TwitchEnabled {
            get {
                return ResourceManager.GetString("TwitchEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitch Redeem:.
        /// </summary>
        public static string TwitchRedeem {
            get {
                return ResourceManager.GetString("TwitchRedeem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the name of the twitch redeem which should trigger the ttspet.
        /// </summary>
        public static string TwitchRedeemToolTip {
            get {
                return ResourceManager.GetString("TwitchRedeemToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of any redeem that should trigger the ttspet.
        /// </summary>
        public static string TwitchRedeemToolTip2 {
            get {
                return ResourceManager.GetString("TwitchRedeemToolTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitch Status:.
        /// </summary>
        public static string TwitchStatus {
            get {
                return ResourceManager.GetString("TwitchStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitch Token lasts until:.
        /// </summary>
        public static string TwitchTokenLasts {
            get {
                return ResourceManager.GetString("TwitchTokenLasts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you will need to refresh this every now and then.
        /// </summary>
        public static string TwitchTokenLastsToolTip {
            get {
                return ResourceManager.GetString("TwitchTokenLastsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitch triggers.
        /// </summary>
        public static string TwitchTriggers {
            get {
                return ResourceManager.GetString("TwitchTriggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Twitch Emotes.
        /// </summary>
        public static string UseTwitchEmotes {
            get {
                return ResourceManager.GetString("UseTwitchEmotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
    }
}
