using CommunityToolkit.Mvvm.ComponentModel;
using CppSharp.Types.Std;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;

namespace PngifyMe.Services.TTSPet.Settings
{
    public partial class StreamElementsTTSSettings : ObservableObject, ITTSSettings
    {
        private StreamElementsVoice voice;

        public StreamElementsVoice Voice
        {
            get
            {
                // Ensure the voice is always up-to-date with the reference list
                if (voice != null)
                {
                    voice = VoiceList.Find(v => v.Voice == voice.Voice);
                }
                return voice;
            }
            set
            {
                SetProperty(ref voice, value);
            }
        }

        //https://lazypy.ro/tts/
        [JsonIgnore]
        public static List<StreamElementsVoice> VoiceList { get; } =
        [
            new StreamElementsVoice(){ Title = "Brian (English, British)", Gender = "M", Api= "StreamElements", Voice = "Brian"},
            new StreamElementsVoice(){ Title = "Amy (English, British)", Gender = "F", Api= "StreamElements", Voice = "Amy"},
            new StreamElementsVoice(){ Title = "Emma (English, British)", Gender = "F", Api= "StreamElements", Voice = "Emma"},
            new StreamElementsVoice(){ Title = "Geraint (English, Welsh)", Gender = "M", Api= "StreamElements", Voice = "Geraint"},
            new StreamElementsVoice(){ Title = "Russell (English, Australian)", Gender = "M", Api= "StreamElements", Voice = "Russell"},
            new StreamElementsVoice(){ Title = "Nicole (English, Australian)", Gender = "F", Api= "StreamElements", Voice = "Nicole"},
            new StreamElementsVoice(){ Title = "Joey (English, American)", Gender = "M", Api= "StreamElements", Voice = "Joey"},
            new StreamElementsVoice(){ Title = "Justin (English, American)", Gender = "M", Api= "StreamElements", Voice = "Justin"},
            new StreamElementsVoice(){ Title = "Matthew (English, American)", Gender = "M", Api= "StreamElements", Voice = "Matthew"},
            new StreamElementsVoice(){ Title = "Ivy (English, American)", Gender = "F", Api= "StreamElements", Voice = "Ivy"},
            new StreamElementsVoice(){ Title = "Joanna (English, American)", Gender = "F", Api= "StreamElements", Voice = "Joanna"},
            new StreamElementsVoice(){ Title = "Kendra (English, American)", Gender = "F", Api= "StreamElements", Voice = "Kendra"},
            new StreamElementsVoice(){ Title = "Kimberly (English, American)", Gender = "F", Api= "StreamElements", Voice = "Kimberly"},
            new StreamElementsVoice(){ Title = "Salli (English, American)", Gender = "F", Api= "StreamElements", Voice = "Salli"},
            new StreamElementsVoice(){ Title = "Raveena (English, Indian)", Gender = "F", Api= "StreamElements", Voice = "Raveena"},
            new StreamElementsVoice(){ Title = "Zhiyu (Chinese, Mandarin)", Gender = "F", Api= "StreamElements", Voice = "Zhiyu"},
            new StreamElementsVoice(){ Title = "Mads (Danish)", Gender = "M", Api= "StreamElements", Voice = "Mads"},
            new StreamElementsVoice(){ Title = "Naja (Danish)", Gender = "F", Api= "StreamElements", Voice = "Naja"},
            new StreamElementsVoice(){ Title = "Ruben (Dutch)", Gender = "M", Api= "StreamElements", Voice = "Ruben"},
            new StreamElementsVoice(){ Title = "Lotte (Polly) (Dutch)", Gender = "F", Api= "StreamElements", Voice = "Lotte"},
            new StreamElementsVoice(){ Title = "Mathieu (French)", Gender = "M", Api= "StreamElements", Voice = "Mathieu"},
            new StreamElementsVoice(){ Title = "Céline (French)", Gender = "F", Api= "StreamElements", Voice = "Celine"},
            new StreamElementsVoice(){ Title = "Chantal (French, Canadian)", Gender = "F", Api= "StreamElements", Voice = "Chantal"},
            new StreamElementsVoice(){ Title = "Hans (German)", Gender = "M", Api= "StreamElements", Voice = "Hans"},
            new StreamElementsVoice(){ Title = "Marlene (German)", Gender = "F", Api= "StreamElements", Voice = "Marlene"},
            new StreamElementsVoice(){ Title = "Vicki (German)", Gender = "F", Api= "StreamElements", Voice = "Vicki"},
            new StreamElementsVoice(){ Title = "Aditi (+English) (Hindi)", Gender = "F", Api= "StreamElements", Voice = "Aditi"},
            new StreamElementsVoice(){ Title = "Karl (Icelandic)", Gender = "M", Api= "StreamElements", Voice = "Karl"},
            new StreamElementsVoice(){ Title = "Dóra (Icelandic)", Gender = "F", Api= "StreamElements", Voice = "Dora"},
            new StreamElementsVoice(){ Title = "Carla (Italian)", Gender = "F", Api= "StreamElements", Voice = "Carla"},
            new StreamElementsVoice(){ Title = "Bianca (Italian)", Gender = "F", Api= "StreamElements", Voice = "Bianca"},
            new StreamElementsVoice(){ Title = "Giorgio (Italian)", Gender = "M", Api= "StreamElements", Voice = "Giorgio"},
            new StreamElementsVoice(){ Title = "Takumi (Japanese)", Gender = "M", Api= "StreamElements", Voice = "Takumi"},
            new StreamElementsVoice(){ Title = "Mizuki (Japanese)", Gender = "F", Api= "StreamElements", Voice = "Mizuki"},
            new StreamElementsVoice(){ Title = "Seoyeon (Korean)", Gender = "F", Api= "StreamElements", Voice = "Seoyeon"},
            new StreamElementsVoice(){ Title = "Liv (Norwegian)", Gender = "F", Api= "StreamElements", Voice = "Liv"},
            new StreamElementsVoice(){ Title = "Ewa (Polish)", Gender = "F", Api= "StreamElements", Voice = "Ewa"},
            new StreamElementsVoice(){ Title = "Maja (Polish)", Gender = "F", Api= "StreamElements", Voice = "Maja"},
            new StreamElementsVoice(){ Title = "Jacek (Polish)", Gender = "M", Api= "StreamElements", Voice = "Jacek"},
            new StreamElementsVoice(){ Title = "Jan (Polish)", Gender = "M", Api= "StreamElements", Voice = "Jan"},
            new StreamElementsVoice(){ Title = "Ricardo (Portuguese, Brazilian)", Gender = "M", Api= "StreamElements", Voice = "Ricardo"},
            new StreamElementsVoice(){ Title = "Vitória (Portuguese, Brazilian)", Gender = "F", Api= "StreamElements", Voice = "Vitoria"},
            new StreamElementsVoice(){ Title = "Cristiano (Portuguese, European)", Gender = "M", Api= "StreamElements", Voice = "Cristiano"},
            new StreamElementsVoice(){ Title = "Inês (Portuguese, European)", Gender = "F", Api= "StreamElements", Voice = "Ines"},
            new StreamElementsVoice(){ Title = "Carmen (Romanian)", Gender = "F", Api= "StreamElements", Voice = "Carmen"},
            new StreamElementsVoice(){ Title = "Maxim (Russian)", Gender = "M", Api= "StreamElements", Voice = "Maxim"},
            new StreamElementsVoice(){ Title = "Tatyana (Russian)", Gender = "F", Api= "StreamElements", Voice = "Tatyana"},
            new StreamElementsVoice(){ Title = "Enrique (Spanish, European)", Gender = "M", Api= "StreamElements", Voice = "Enrique"},
            new StreamElementsVoice(){ Title = "Conchita (Spanish, European)", Gender = "F", Api= "StreamElements", Voice = "Conchita"},
            new StreamElementsVoice(){ Title = "Mia (Spanish, Mexican)", Gender = "F", Api= "StreamElements", Voice = "Mia"},
            new StreamElementsVoice(){ Title = "Miguel (Spanish, American)", Gender = "M", Api= "StreamElements", Voice = "Miguel"},
            new StreamElementsVoice(){ Title = "Penélope (Spanish, American)", Gender = "F", Api= "StreamElements", Voice = "Penelope"},
            new StreamElementsVoice(){ Title = "Astrid (Swedish)", Gender = "F", Api= "StreamElements", Voice = "Astrid"},
            new StreamElementsVoice(){ Title = "Filiz (Turkish)", Gender = "M", Api= "StreamElements", Voice = "Filiz"},
            new StreamElementsVoice(){ Title = "Gwyneth (Welsh)", Gender = "F", Api= "StreamElements", Voice = "Gwyneth"},
            new StreamElementsVoice(){ Title = "Carter (English, American)", Gender = "M", Api= "StreamElements", Voice = "en-US-Wavenet-A"},
            new StreamElementsVoice(){ Title = "Paul (English, American)", Gender = "M", Api= "StreamElements", Voice = "en-US-Wavenet-B"},
            new StreamElementsVoice(){ Title = "Evelyn (English, American)", Gender = "F", Api= "StreamElements", Voice = "en-US-Wavenet-C"},
            new StreamElementsVoice(){ Title = "Liam (English, American)", Gender = "M", Api= "StreamElements", Voice = "en-US-Wavenet-D"},
            new StreamElementsVoice(){ Title = "Jasmine (English, American)", Gender = "F", Api= "StreamElements", Voice = "en-US-Wavenet-E"},
            new StreamElementsVoice(){ Title = "Madison (English, American)", Gender = "F", Api= "StreamElements", Voice = "en-US-Wavenet-F"},
            new StreamElementsVoice(){ Title = "Mark (English, American)", Gender = "M", Api= "StreamElements", Voice = "en-US-Standard-B"},
            new StreamElementsVoice(){ Title = "Vanessa (English, American)", Gender = "F", Api= "StreamElements", Voice = "en-US-Standard-C"},
            new StreamElementsVoice(){ Title = "Zachary (English, American)", Gender = "M", Api= "StreamElements", Voice = "en-US-Standard-D"},
            new StreamElementsVoice(){ Title = "Audrey (English, American)", Gender = "F", Api= "StreamElements", Voice = "en-US-Standard-E"},
            new StreamElementsVoice(){ Title = "Layla (English, British)", Gender = "F", Api= "StreamElements", Voice = "en-GB-Standard-A"},
            new StreamElementsVoice(){ Title = "Ali (English, British)", Gender = "M", Api= "StreamElements", Voice = "en-GB-Standard-B"},
            new StreamElementsVoice(){ Title = "Scarlett (English, British)", Gender = "F", Api= "StreamElements", Voice = "en-GB-Standard-C"},
            new StreamElementsVoice(){ Title = "Oliver (English, British)", Gender = "M", Api= "StreamElements", Voice = "en-GB-Standard-D"},
            new StreamElementsVoice(){ Title = "Bella (English, British)", Gender = "F", Api= "StreamElements", Voice = "en-GB-Wavenet-A"},
            new StreamElementsVoice(){ Title = "John (English, British)", Gender = "M", Api= "StreamElements", Voice = "en-GB-Wavenet-B"},
            new StreamElementsVoice(){ Title = "Victoria (English, British)", Gender = "F", Api= "StreamElements", Voice = "en-GB-Wavenet-C"},
            new StreamElementsVoice(){ Title = "Ron (English, British)", Gender = "M", Api= "StreamElements", Voice = "en-GB-Wavenet-D"},
            new StreamElementsVoice(){ Title = "Zoe (English, Australian)", Gender = "F", Api= "StreamElements", Voice = "en-AU-Standard-A"},
            new StreamElementsVoice(){ Title = "Luke (English, Australian)", Gender = "M", Api= "StreamElements", Voice = "en-AU-Standard-B"},
            new StreamElementsVoice(){ Title = "Samantha (English, Australian)", Gender = "F", Api= "StreamElements", Voice = "en-AU-Wavenet-A"},
            new StreamElementsVoice(){ Title = "Steve (English, Australian)", Gender = "M", Api= "StreamElements", Voice = "en-AU-Wavenet-B"},
            new StreamElementsVoice(){ Title = "Courtney (English, Australian)", Gender = "F", Api= "StreamElements", Voice = "en-AU-Wavenet-C"},
            new StreamElementsVoice(){ Title = "Jayden (English, Australian)", Gender = "M", Api= "StreamElements", Voice = "en-AU-Wavenet-D"},
            new StreamElementsVoice(){ Title = "Ashleigh (English, Australian)", Gender = "F", Api= "StreamElements", Voice = "en-AU-Standard-C"},
            new StreamElementsVoice(){ Title = "Daniel (English, Australian)", Gender = "M", Api= "StreamElements", Voice = "en-AU-Standard-D"},
            new StreamElementsVoice(){ Title = "Anushri (English, Indian)", Gender = "F", Api= "StreamElements", Voice = "en-IN-Wavenet-A"},
            new StreamElementsVoice(){ Title = "Sundar (English, Indian)", Gender = "M", Api= "StreamElements", Voice = "en-IN-Wavenet-B"},
            new StreamElementsVoice(){ Title = "Satya (English, Indian)", Gender = "M", Api= "StreamElements", Voice = "en-IN-Wavenet-C"},
            new StreamElementsVoice(){ Title = "Sonya (Afrikaans)", Gender = "F", Api= "StreamElements", Voice = "af-ZA-Standard-A"},
            new StreamElementsVoice(){ Title = "Aisha (Arabic)", Gender = "F", Api= "StreamElements", Voice = "ar-XA-Wavenet-A"},
            new StreamElementsVoice(){ Title = "Ahmad 1 (Arabic)", Gender = "M", Api= "StreamElements", Voice = "ar-XA-Wavenet-B"},
            new StreamElementsVoice(){ Title = "Ahmad 2 (Arabic)", Gender = "M", Api= "StreamElements", Voice = "ar-XA-Wavenet-C"},
            new StreamElementsVoice(){ Title = "Nikolina (Bulgarian)", Gender = "F", Api= "StreamElements", Voice = "bg-bg-Standard-A"},
            new StreamElementsVoice(){ Title = "Li Na (Chinese, Mandarin)", Gender = "F", Api= "StreamElements", Voice = "cmn-CN-Wavenet-A"},
            new StreamElementsVoice(){ Title = "Wang (Chinese, Mandarin)", Gender = "M", Api= "StreamElements", Voice = "cmn-CN-Wavenet-B"},
            new StreamElementsVoice(){ Title = "Bai (Chinese, Mandarin)", Gender = "M", Api= "StreamElements", Voice = "cmn-CN-Wavenet-C"},
            new StreamElementsVoice(){ Title = "Mingli (Chinese, Mandarin)", Gender = "F", Api= "StreamElements", Voice = "cmn-CN-Wavenet-D"},
            new StreamElementsVoice(){ Title = "Silvia (Czech)", Gender = "F", Api= "StreamElements", Voice = "cs-CZ-Wavenet-A"},
            new StreamElementsVoice(){ Title = "Marie (Danish)", Gender = "F", Api= "StreamElements", Voice = "da-DK-Wavenet-A"},
            new StreamElementsVoice(){ Title = "Annemieke (Dutch)", Gender = "F", Api= "StreamElements", Voice = "nl-NL-Standard-A"},
            new StreamElementsVoice(){ Title = "Eva (Dutch)", Gender = "F", Api= "StreamElements", Voice = "nl-NL-Wavenet-A"},
            new StreamElementsVoice(){ Title = "Lars (Dutch)", Gender = "M", Api= "StreamElements", Voice = "nl-NL-Wavenet-B"},
            new StreamElementsVoice(){ Title = "Marc (Dutch)", Gender = "M", Api= "StreamElements", Voice = "nl-NL-Wavenet-C"},
            new StreamElementsVoice(){ Title = "Verona (Dutch)", Gender = "F", Api= "StreamElements", Voice = "nl-NL-Wavenet-D"},
            new StreamElementsVoice(){ Title = "Lotte (Wavenet) (Dutch)", Gender = "F", Api= "StreamElements", Voice = "nl-NL-Wavenet-E"},
            new StreamElementsVoice(){ Title = "Tala (Filipino (Tagalog))", Gender = "F", Api= "StreamElements", Voice = "fil-PH-Wavenet-A"},
            new StreamElementsVoice(){ Title = "Marianne (Finnish)", Gender = "F", Api= "StreamElements", Voice = "fi-FI-Wavenet-A"},
            new StreamElementsVoice(){ Title = "Yvonne (French)", Gender = "F", Api= "StreamElements", Voice = "fr-FR-Standard-C"},
            new StreamElementsVoice(){ Title = "Gaspard (French)", Gender = "M", Api= "StreamElements", Voice = "fr-FR-Standard-D"},
            new StreamElementsVoice(){ Title = "Emilie (French)", Gender = "F", Api= "StreamElements", Voice = "fr-FR-Wavenet-A"},
            new StreamElementsVoice(){ Title = "Marcel (French)", Gender = "M", Api= "StreamElements", Voice = "fr-FR-Wavenet-B"},
            new StreamElementsVoice(){ Title = "Brigitte (French)", Gender = "F", Api= "StreamElements", Voice = "fr-FR-Wavenet-C"},
            new StreamElementsVoice(){ Title = "Simon (French)", Gender = "M", Api= "StreamElements", Voice = "fr-FR-Wavenet-D"},
            new StreamElementsVoice(){ Title = "Juliette (French, Canadian)", Gender = "F", Api= "StreamElements", Voice = "fr-CA-Standard-A"},
            new StreamElementsVoice(){ Title = "Felix (French, Canadian)", Gender = "M", Api= "StreamElements", Voice = "fr-CA-Standard-B"},
            new StreamElementsVoice(){ Title = "Camille (French, Canadian)", Gender = "F", Api= "StreamElements", Voice = "fr-CA-Standard-C"},
            new StreamElementsVoice(){ Title = "Jacques (French, Canadian)", Gender = "M", Api= "StreamElements", Voice = "fr-CA-Standard-D"},
            new StreamElementsVoice(){ Title = "Karolina (German)", Gender = "F", Api= "StreamElements", Voice = "de-DE-Standard-A"},
            new StreamElementsVoice(){ Title = "Albert (German)", Gender = "M", Api= "StreamElements", Voice = "de-DE-Standard-B"},
            new StreamElementsVoice(){ Title = "Angelika (German)", Gender = "F", Api= "StreamElements", Voice = "de-DE-Wavenet-A"},
            new StreamElementsVoice(){ Title = "Oskar (German)", Gender = "M", Api= "StreamElements", Voice = "de-DE-Wavenet-B"},
            new StreamElementsVoice(){ Title = "Nina (German)", Gender = "F", Api= "StreamElements", Voice = "de-DE-Wavenet-C"},
            new StreamElementsVoice(){ Title = "Sebastian (German)", Gender = "M", Api= "StreamElements", Voice = "de-DE-Wavenet-D"},
            new StreamElementsVoice(){ Title = "Thalia (Greek)", Gender = "F", Api= "StreamElements", Voice = "el-GR-Wavenet-A"},
            new StreamElementsVoice(){ Title = "Sneha (Hindi)", Gender = "F", Api= "StreamElements", Voice = "hi-IN-Wavenet-A"},
            new StreamElementsVoice(){ Title = "Arnav (Hindi)", Gender = "M", Api= "StreamElements", Voice = "hi-IN-Wavenet-B"},
            new StreamElementsVoice(){ Title = "Aadhav (Hindi)", Gender = "M", Api= "StreamElements", Voice = "hi-IN-Wavenet-C"},
            new StreamElementsVoice(){ Title = "Ishtevan (Hungarian)", Gender = "F", Api= "StreamElements", Voice = "hu-HU-Wavenet-A"},
            new StreamElementsVoice(){ Title = "Helga (Icelandic)", Gender = "F", Api= "StreamElements", Voice = "is-is-Standard-A"},
            new StreamElementsVoice(){ Title = "Anisa (Indonesian)", Gender = "F", Api= "StreamElements", Voice = "id-ID-Wavenet-A"},
            new StreamElementsVoice(){ Title = "Budi (Indonesian)", Gender = "M", Api= "StreamElements", Voice = "id-ID-Wavenet-B"},
            new StreamElementsVoice(){ Title = "Bayu (Indonesian)", Gender = "M", Api= "StreamElements", Voice = "id-ID-Wavenet-C"},
            new StreamElementsVoice(){ Title = "Gianna (Italian)", Gender = "F", Api= "StreamElements", Voice = "it-IT-Standard-A"},
            new StreamElementsVoice(){ Title = "Valentina (Italian)", Gender = "F", Api= "StreamElements", Voice = "it-IT-Wavenet-A"},
            new StreamElementsVoice(){ Title = "Stella (Italian)", Gender = "F", Api= "StreamElements", Voice = "it-IT-Wavenet-B"},
            new StreamElementsVoice(){ Title = "Alessandro (Italian)", Gender = "M", Api= "StreamElements", Voice = "it-IT-Wavenet-C"},
            new StreamElementsVoice(){ Title = "Luca (Italian)", Gender = "M", Api= "StreamElements", Voice = "it-IT-Wavenet-D"},
            new StreamElementsVoice(){ Title = "Koharu (Japanese)", Gender = "F", Api= "StreamElements", Voice = "ja-JP-Standard-A"},
            new StreamElementsVoice(){ Title = "Miho (Japanese)", Gender = "F", Api= "StreamElements", Voice = "ja-JP-Wavenet-A"},
            new StreamElementsVoice(){ Title = "Eiko (Japanese)", Gender = "F", Api= "StreamElements", Voice = "ja-JP-Wavenet-B"},
            new StreamElementsVoice(){ Title = "Haruto (Japanese)", Gender = "M", Api= "StreamElements", Voice = "ja-JP-Wavenet-C"},
            new StreamElementsVoice(){ Title = "Eichi (Japanese)", Gender = "M", Api= "StreamElements", Voice = "ja-JP-Wavenet-D"},
            new StreamElementsVoice(){ Title = "Heosu (Korean)", Gender = "F", Api= "StreamElements", Voice = "ko-KR-Standard-A"},
            new StreamElementsVoice(){ Title = "Grace (Korean)", Gender = "F", Api= "StreamElements", Voice = "ko-KR-Wavenet-A"},
            new StreamElementsVoice(){ Title = "Juris (Latvian)", Gender = "M", Api= "StreamElements", Voice = "lv-lv-Standard-A"},
            new StreamElementsVoice(){ Title = "Nora (Norwegian, Bokmål)", Gender = "F", Api= "StreamElements", Voice = "nb-no-Wavenet-E"},
            new StreamElementsVoice(){ Title = "Malena (Norwegian, Bokmål)", Gender = "F", Api= "StreamElements", Voice = "nb-no-Wavenet-A"},
            new StreamElementsVoice(){ Title = "Jacob (Norwegian, Bokmål)", Gender = "M", Api= "StreamElements", Voice = "nb-no-Wavenet-B"},
            new StreamElementsVoice(){ Title = "Thea (Norwegian, Bokmål)", Gender = "F", Api= "StreamElements", Voice = "nb-no-Wavenet-C"},
            new StreamElementsVoice(){ Title = "Aksel (Norwegian, Bokmål)", Gender = "M", Api= "StreamElements", Voice = "nb-no-Wavenet-D"},
            new StreamElementsVoice(){ Title = "Amelia (Polish)", Gender = "F", Api= "StreamElements", Voice = "pl-PL-Wavenet-A"},
            new StreamElementsVoice(){ Title = "Stanislaw (Polish)", Gender = "M", Api= "StreamElements", Voice = "pl-PL-Wavenet-B"},
            new StreamElementsVoice(){ Title = "Tomasz (Polish)", Gender = "M", Api= "StreamElements", Voice = "pl-PL-Wavenet-C"},
            new StreamElementsVoice(){ Title = "Klaudia (Polish)", Gender = "F", Api= "StreamElements", Voice = "pl-PL-Wavenet-D"},
            new StreamElementsVoice(){ Title = "Beatriz (Portuguese, Portugal)", Gender = "F", Api= "StreamElements", Voice = "pt-PT-Wavenet-A"},
            new StreamElementsVoice(){ Title = "Francisco (Portuguese, Portugal)", Gender = "M", Api= "StreamElements", Voice = "pt-PT-Wavenet-B"},
            new StreamElementsVoice(){ Title = "Lucas (Portuguese, Portugal)", Gender = "M", Api= "StreamElements", Voice = "pt-PT-Wavenet-C"},
            new StreamElementsVoice(){ Title = "Carolina (Portuguese, Portugal)", Gender = "F", Api= "StreamElements", Voice = "pt-PT-Wavenet-D"},
            new StreamElementsVoice(){ Title = "Alice (Portuguese, Brazilian)", Gender = "F", Api= "StreamElements", Voice = "pt-BR-Standard-A"},
            new StreamElementsVoice(){ Title = "Маша (Masha) (Russian)", Gender = "F", Api= "StreamElements", Voice = "ru-RU-Wavenet-A"},
            new StreamElementsVoice(){ Title = "Илья (Ilya) (Russian)", Gender = "M", Api= "StreamElements", Voice = "ru-RU-Wavenet-B"},
            new StreamElementsVoice(){ Title = "Алёна (Alena) (Russian)", Gender = "F", Api= "StreamElements", Voice = "ru-RU-Wavenet-C"},
            new StreamElementsVoice(){ Title = "Пётр (Petr) (Russian)", Gender = "M", Api= "StreamElements", Voice = "ru-RU-Wavenet-D"},
            new StreamElementsVoice(){ Title = "Aleksandra (Serbian)", Gender = "F", Api= "StreamElements", Voice = "sr-rs-Standard-A"},
            new StreamElementsVoice(){ Title = "Eliska (Slovak)", Gender = "F", Api= "StreamElements", Voice = "sk-SK-Wavenet-A"},
            new StreamElementsVoice(){ Title = "Rosalinda (Spanish, Castilian)", Gender = "F", Api= "StreamElements", Voice = "es-ES-Standard-A"},
            new StreamElementsVoice(){ Title = "Elsa (Swedish)", Gender = "F", Api= "StreamElements", Voice = "sv-SE-Standard-A"},
            new StreamElementsVoice(){ Title = "Zehra (Turkish)", Gender = "F", Api= "StreamElements", Voice = "tr-TR-Standard-A"},
            new StreamElementsVoice(){ Title = "Yagmur (Turkish)", Gender = "F", Api= "StreamElements", Voice = "tr-TR-Wavenet-A"},
            new StreamElementsVoice(){ Title = "Mehmet (Turkish)", Gender = "M", Api= "StreamElements", Voice = "tr-TR-Wavenet-B"},
            new StreamElementsVoice(){ Title = "Miray (Turkish)", Gender = "F", Api= "StreamElements", Voice = "tr-TR-Wavenet-C"},
            new StreamElementsVoice(){ Title = "Elif (Turkish)", Gender = "F", Api= "StreamElements", Voice = "tr-TR-Wavenet-D"},
            new StreamElementsVoice(){ Title = "Enes (Turkish)", Gender = "M", Api= "StreamElements", Voice = "tr-TR-Wavenet-E"},
            new StreamElementsVoice(){ Title = "Vladislava (Ukrainian)", Gender = "F", Api= "StreamElements", Voice = "uk-UA-Wavenet-A"},
            new StreamElementsVoice(){ Title = "Linh (Vietnamese)", Gender = "F", Api= "StreamElements", Voice = "vi-VN-Wavenet-A"},
            new StreamElementsVoice(){ Title = "Nguyen (Vietnamese)", Gender = "M", Api= "StreamElements", Voice = "vi-VN-Wavenet-B"},
            new StreamElementsVoice(){ Title = "Phuong (Vietnamese)", Gender = "F", Api= "StreamElements", Voice = "vi-VN-Wavenet-C"},
            new StreamElementsVoice(){ Title = "Viet (Vietnamese)", Gender = "M", Api= "StreamElements", Voice = "vi-VN-Wavenet-D"},
            new StreamElementsVoice(){ Title = "Linda (English, Canadian)", Gender = "F", Api= "StreamElements", Voice = "Linda"},
            new StreamElementsVoice(){ Title = "Heather (English, Canadian)", Gender = "F", Api= "StreamElements", Voice = "Heather"},
            new StreamElementsVoice(){ Title = "Sean (English, Irish)", Gender = "M", Api= "StreamElements", Voice = "Sean"},
            new StreamElementsVoice(){ Title = "Hoda (Arabic, Egypt)", Gender = "F", Api= "StreamElements", Voice = "Hoda"},
            new StreamElementsVoice(){ Title = "Naayf (Arabic, Saudi Arabia)", Gender = "M", Api= "StreamElements", Voice = "Naayf"},
            new StreamElementsVoice(){ Title = "Ivan (Bulgarian)", Gender = "M", Api= "StreamElements", Voice = "Ivan"},
            new StreamElementsVoice(){ Title = "Herena (Catalan)", Gender = "F", Api= "StreamElements", Voice = "Herena"},
            new StreamElementsVoice(){ Title = "Tracy (Chinese, Cantonese, Traditional)", Gender = "F", Api= "StreamElements", Voice = "Tracy"},
            new StreamElementsVoice(){ Title = "Danny (Chinese, Cantonese, Traditional)", Gender = "M", Api= "StreamElements", Voice = "Danny"},
            new StreamElementsVoice(){ Title = "Huihui (Chinese, Mandarin, Simplified)", Gender = "F", Api= "StreamElements", Voice = "Huihui"},
            new StreamElementsVoice(){ Title = "Yaoyao (Chinese, Mandarin, Simplified)", Gender = "M", Api= "StreamElements", Voice = "Yaoyao"},
            new StreamElementsVoice(){ Title = "Kangkang (Chinese, Mandarin, Simplified)", Gender = "M", Api= "StreamElements", Voice = "Kangkang"},
            new StreamElementsVoice(){ Title = "HanHan (Chinese, Taiwanese, Traditional)", Gender = "F", Api= "StreamElements", Voice = "HanHan"},
            new StreamElementsVoice(){ Title = "Zhiwei (Chinese, Taiwanese, Traditional)", Gender = "F", Api= "StreamElements", Voice = "Zhiwei"},
            new StreamElementsVoice(){ Title = "Matej (Croatian)", Gender = "M", Api= "StreamElements", Voice = "Matej"},
            new StreamElementsVoice(){ Title = "Jakub (Czech)", Gender = "M", Api= "StreamElements", Voice = "Jakub"},
            new StreamElementsVoice(){ Title = "Guillaume (French, Switzerland)", Gender = "M", Api= "StreamElements", Voice = "Guillaume"},
            new StreamElementsVoice(){ Title = "Michael (German, Austria)", Gender = "M", Api= "StreamElements", Voice = "Michael"},
            new StreamElementsVoice(){ Title = "Karsten (German, Switzerland)", Gender = "M", Api= "StreamElements", Voice = "Karsten"},
            new StreamElementsVoice(){ Title = "Stefanos (Greek)", Gender = "M", Api= "StreamElements", Voice = "Stefanos"},
            new StreamElementsVoice(){ Title = "Szabolcs (Hungarian)", Gender = "M", Api= "StreamElements", Voice = "Szabolcs"},
            new StreamElementsVoice(){ Title = "Andika (Indonesian)", Gender = "F", Api= "StreamElements", Voice = "Andika"},
            new StreamElementsVoice(){ Title = "Heidi (Finnish)", Gender = "F", Api= "StreamElements", Voice = "Heidi"},
            new StreamElementsVoice(){ Title = "Kalpana (Hindi)", Gender = "F", Api= "StreamElements", Voice = "Kalpana"},
            new StreamElementsVoice(){ Title = "Hemant (Hindi)", Gender = "M", Api= "StreamElements", Voice = "Hemant"},
            new StreamElementsVoice(){ Title = "Rizwan (Malay)", Gender = "M", Api= "StreamElements", Voice = "Rizwan"},
            new StreamElementsVoice(){ Title = "Filip (Slovak)", Gender = "M", Api= "StreamElements", Voice = "Filip"},
            new StreamElementsVoice(){ Title = "Lado (Slovenian)", Gender = "M", Api= "StreamElements", Voice = "Lado"},
            new StreamElementsVoice(){ Title = "Valluvar (Tamil, India)", Gender = "M", Api= "StreamElements", Voice = "Valluvar"},
            new StreamElementsVoice(){ Title = "Pattara (Thai)", Gender = "M", Api= "StreamElements", Voice = "Pattara"},
            new StreamElementsVoice(){ Title = "An (Vietnamese)", Gender = "M", Api= "StreamElements", Voice = "An"},
        ];

        public StreamElementsTTSSettings()
        {
            voice = VoiceList.First();
        }
    }

    public class StreamElementsVoice
    {
        public string Title { get; set; }
        public string Voice { get; set; }
        public string Gender { get; set; }
        public string Api { get; set; }
    }
}
